In [20]:
import numpy as np
K_11 = np.array([2,3,5,6])
print(K_11)
E_11 = np.array([[2,3,4,5],[8,7,6,5]])
print(E_11)
T_11 = np.array([[[1,2,3,4],[4,3,2,1]],
               [[5,6,7,8],[8,7,6,5]],
               [[9,0,1,2],[2,1,0,9]]])
print(T_11)

[2 3 5 6]
[[2 3 4 5]
 [8 7 6 5]]
[[[1 2 3 4]
  [4 3 2 1]]

 [[5 6 7 8]
  [8 7 6 5]]

 [[9 0 1 2]
  [2 1 0 9]]]


1

In [27]:
T_11.ndim

3

In [28]:
E_11.shape

(2, 4)

In [31]:
U_11 = np.array([[0,2,1,5],[5,3,4,2],[7,6,9,4],[6,3,5,4]])
print(U_11)
U_11[1,3]

[[0 2 1 5]
 [5 3 4 2]
 [7 6 9 4]
 [6 3 5 4]]


2

In [32]:
U_11[3,:]

array([6, 3, 5, 4])

In [34]:
U_11[:,3]

array([5, 2, 4, 4])

In [36]:
U_11[1,0:2:1]

array([5, 3])

In [40]:
#Kolom dan baris dengan bil 0
G_11 = np.zeros((5,5))
print(G_11)
#Menambahkan identitas pd matriks
I_11 = np.identity(5)
print(I_11)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [41]:
#Kolom dan baris dengan bil 1
T_11 = np.ones((3,4))
print(T_11)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [46]:
#Membuat 2 buah matriks dengan baris dan kolom dg bilangan yang sama
A_11 = np.full((2,3,4),5)
print(A_11)

[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]]


In [47]:
#Membuat matriks dengan bilangan bulat acak
S_11 = np.random.randint(2,6, size=(2,3))
print(S_11)

[[5 3 5]
 [5 5 2]]


In [59]:
R_11 = np.array([0,2,1,5,3])
print(R_11)
I_11 = R_11
print(I_11)
#Mengganti bil pada matriks
I_11[3] = 9
print(I_11)
print(R_11)

[0 2 1 5 3]
[0 2 1 5 3]
[0 2 1 9 3]
[0 2 1 9 3]


In [3]:
import numpy as np
N_11 = np.array([1,2,3,4,5])
N_11*2

array([3, 4, 5, 6, 7])

In [4]:
N_11+2

array([3, 4, 5, 6, 7])

In [5]:
E_11 = np.array([1,2,5,6,9])
N_11*E_11

array([ 1,  4, 15, 24, 45])

In [16]:
#11_Membuat matriks menggunakan np
import numpy as np
G_11 = np.ones((6,6))
print(G_11)
I_11 = np.identity(6)*5
print(I_11)
g_11 = np.ones((4,4))
i_11 = np.identity(4)*5
T_11 = g_11+i_11
print(T_11)
I_11[1:-1,1:-1] = T_11
print(I_11)
A_11 = np.zeros((2,2))
print(A_11)
I_11[2:-2,2:-2] = A_11
print(I_11)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[5. 0. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0. 0.]
 [0. 0. 5. 0. 0. 0.]
 [0. 0. 0. 5. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 5.]]
[[6. 1. 1. 1.]
 [1. 6. 1. 1.]
 [1. 1. 6. 1.]
 [1. 1. 1. 6.]]
[[5. 0. 0. 0. 0. 0.]
 [0. 6. 1. 1. 1. 0.]
 [0. 1. 6. 1. 1. 0.]
 [0. 1. 1. 6. 1. 0.]
 [0. 1. 1. 1. 6. 0.]
 [0. 0. 0. 0. 0. 5.]]
[[0. 0.]
 [0. 0.]]
[[5. 0. 0. 0. 0. 0.]
 [0. 6. 1. 1. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 1. 1. 6. 0.]
 [0. 0. 0. 0. 0. 5.]]


In [15]:
##11_Hasil matriks
I_11[2:-2,2:-2] = A_11
print(I_11)

[[5. 0. 0. 0. 0. 0.]
 [0. 6. 1. 1. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 1. 1. 1. 6. 0.]
 [0. 0. 0. 0. 0. 5.]]


In [1]:
import numpy as np
Y_11 = np.array([[1,2,4,5],[6,3,7,8]])
print(Y_11)
V_11 = np.array([[8,9,7,6],[4,3,6,5]])
print(V_11)
Z_11 = Y_11*V_11
print(Z_11)

[[1 2 4 5]
 [6 3 7 8]]
[[8 9 7 6]
 [4 3 6 5]]
[[ 8 18 28 30]
 [24  9 42 40]]


In [25]:
import numpy as np
B_11 = np.array([[0,9,8,7],
                [6,5,4,3],
                [2,1,2,3]])
print(B_11)
C_11 = np.min(B_11)
print(C_11)
D_11 = np.min(B_11,axis=1)
print(D_11)
F_11 = np.max(B_11)
print(F_11)
H_11 = np.max(B_11,axis=0)
print(H_11)
J_11 = np.sum(B_11)
print(J_11)
L_11 = np.sum(B_11,axis=0)
print(L_11)

[[0 9 8 7]
 [6 5 4 3]
 [2 1 2 3]]
0
[0 3 1]
9
[6 9 8 7]
50
[ 8 15 14 13]
